name: Cache Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 🧱 Cache step
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-56d915c

      # 👇 Required step with the specified name
      - name: prime-cache-56d915c
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"
